add curvebs volume target blocksize
opencurve/curveadm pull request #161
Opened 2022-11-19 12:40 UTC by mfordjody

issues https://github.com/opencurve/curveadm/issues/150

I won't solve the container error
```
[root@client-host curveadm]# go run main.go target add -h
Usage:  curveadm target add USER:VOLUME [OPTIONS]

Add a target of CurveBS

Options:
      --blocksize string   Specify target volume block size (default "512byte")
  -c, --conf string        Specify client configuration file (default "client.yaml")
      --create             Create volume iff not exist
  -h, --help               Print usage
      --host string        Specify target host (default "localhost")
      --size string        Specify volume size (default "10GB")
```
```
[root@client-host curveadm]# go run main.go target add curve:/etc --host server-host1 --create --blocksize 512
---
Error-Code: 201009
Error-Description: volume block size must end with "byte" suffix
Error-Clue: blocksize: 512
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno2#201009
  * Log: /root/.curveadm/logs/curveadm-2022-11-19_04-48-02.log
  * WeChat: opencurve_bot
exit status 1
```
```
go run main.go target add curve:/etc --host server-host1 --create --blocksize 512byte
Add Target: [ERROR]
  + host=server-host1  volume=/etc [0/1] [ERROR]
---
Error-Code: 630009
Error-Description: run a command in container failed (docker exec CONTAINER COMMAND)
Error-Clue: Process exited with status 1
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno6#630009
  * Log: /root/.curveadm/logs/curveadm-2022-11-19_04-48-26.log
  * WeChat: opencurve_bot
exit status 1
```

2022-11-20 08:16 UTC, mfordjody commented
I have to enter the container to debug the code

2022-11-21 08:27 UTC, Cyber-SiKu commented
It should be that you made an error executing the command in the container, and you can enter the container to execute the corresponding command. Or check whether the incoming command is wrong. The way to execute the command is: docker exec -t xxx xxx.

2022-11-21 14:10 UTC, mfordjody commented
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test --host server-hosts --create --blocksize 4096byte
Add Target: [OK]
  + host=server-hosts  volume=/test [1/1] [OK]

Add target (curve:/test) to server-hosts success ^_^
curve@client-hosts:~/curveadm/cmd/curveadm$ curveadm target list --host server-hosts
List Targets: [OK]
  + host=192.168.10.136 [1/1] [OK]

Tid  Host          Target Name                                                       Store                  Portal
---  ----          -----------                                                       -----                  ------
1    server-hosts  iqn.2022-11.com.opencurve:curve.5a82e0b942bc472fe1de2059b971b7bd  cbd:pool//test_curve_  192.168.10.136:3260
```

2022-11-21 15:29 UTC, mfordjody commented
issues https://github.com/opencurve/curveadm/issues/150
Problem solved
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add -h
Usage:  curveadm target add USER:VOLUME [OPTIONS]

Add a target of CurveBS

Options:
      --blocksize string   Specify volume block size (default "512byte")
  -c, --conf string        Specify client configuration file (default "client.yaml")
      --create             Create volume if not exist
  -h, --help               Print usage
      --host string        Specify target host (default "localhost")
      --size string        Specify volume size (default "10GB")
```
```

```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test --host server-hosts --create --blocksize 4096byte
Add Target: [OK]
  + host=server-hosts  volume=/test [1/1] [OK]

Add target (curve:/test) to server-hosts success ^_^
curve@client-hosts:~/curveadm/cmd/curveadm$ curveadm target list --host server-hosts
List Targets: [OK]
  + host=192.168.10.136 [1/1] [OK]

Tid  Host          Target Name                                                       Store                  Portal
---  ----          -----------                                                       -----                  ------
1    server-hosts  iqn.2022-11.com.opencurve:curve.5a82e0b942bc472fe1de2059b971b7bd  cbd:pool//test_curve_  192.168.10.136:3260
```

2022-11-22 05:59 UTC, cw123 commented on internal/task/scripts/target.go
> +    output=$(curve_ops_tool create -userName=$g_user -fileName=$g_volume -fileLength=$g_size -fileLength=$g_blocksize)
-fileLength=$g_blocksize

这里是不是写错了？Is the logic wrong here?

two file length？

2022-11-22 06:01 UTC, cw123 commented
Merge multiple commits into one.

Can this value be read from a configuration file? Add the default value in the conf

2022-11-22 06:45 UTC, mfordjody commented on internal/task/scripts/target.go
> +    output=$(curve_ops_tool create -userName=$g_user -fileName=$g_volume -fileLength=$g_size -fileLength=$g_blocksize)
If I output an error
```
curveadm target add curve:/test --host server-hosts --create --blocksize 4096byte
```
There is this `-fileLength=$g_blocksize`，Will print according to the size

```
$ cat ~/.curveadm/logs/curveadm-2022-11-21_17-45-44.log

    remoteAddr: curve@192.168.10.136:22
    command: sudo docker exec  curvebs-target-daemon /bin/bash /curvebs/tools/sbin/target.sh curve /data true 10 4096
    output:
    error: Process exited with status 1
```
If don't have this `-fileLength=$g_blocksize`，
```
$ cat ~/.curveadm/logs/curveadm-2022-11-21_17-47-23.log

    remoteAddr: curve@192.168.10.136:22
    command: sudo docker exec  curvebs-target-daemon /bin/bash /curvebs/tools/sbin/target.sh curve /data true 10 512
    output:
    error: Process exited with status 1
```

2022-11-22 09:43 UTC, cw123 commented
blocksize 不是在curve_ops_tool create的时候指定的，curve_ops_tool没有指定blocksize的地方。

The blocksize is not specified when the curve_ops_tool create, and the curve_ops_tool does not have the blocksize param.

```
$ curve_ops_tool create --example
Example:
curve_ops_tool create -mdsAddr=127.0.0.1:6666 -fileName=/test -userName=test -password=123 -fileLength=20‬
```

blocksize是在这里指定的，在这个命令的后面添加一个--blocksize $g_blocksize

blocksize is specified here, add a --blocksize $g_blocksize after this command

```
tgtadm --lld iscsi \
    --mode logicalunit \
    --op new \
    --tid ${g_tid} \
    --lun 1 \
    --bstype curve \
    --backing-store ${g_image}
```

为什么要这样修改，因为curvebs在一些版本需要保证下发的请求是4KB对齐的请求，如果用户下发一个非4KB对齐的请求到curvebs，就会出错。通过nbd挂载的设备可以保证，nbd给到curvebs的请求是4KB对齐的，而现在使用target的方式挂载的设备没有对这个做一个保证。在target 添加lun的时候，指定blocksize，可以保证所有的请求都是指定blocksize下来的。

希望这个值默认是4KB。添加target的时候，如果不指定这个命令，就按照4096字节作为blocksize。如果指定blocksize，就按照指定的blocksize。

Why do we want to modify it like this, because in some versions of curvebs, you need to ensure that the issued request is a 4KB-aligned request. If the user sends a non-4KB-aligned request to curvebs, an error will occur. The device mounted through nbd can guarantee that the request from nbd to curvebs is 4KB aligned, but the device mounted using the target method does not make a guarantee for this. When adding a lun to the target, specify the blocksize to ensure that all requests come from the specified blocksize.

Hopefully this value defaults to 4KB. When adding a target, if this command is not specified, 4096 bytes will be used as the blocksize. If blocksize is specified, follow the specified blocksize.

使用的地方参考文档

Reference documents

https://github.com/opencurve/curveadm/wiki/curve-tgt-deployment#%E7%AC%AC-5-%E6%AD%A5%E6%B7%BB%E5%8A%A0-target

```
$ curveadm target add <user>:<volume-name> --host target-host --create --size 10GB
```

2022-11-22 09:55 UTC, cw123 commented
如果未指定blocksize，fdisk -l 看到的可能是这样的

If blocksize is not specified, fdisk -l may see something like this

![image](https://user-images.githubusercontent.com/4277834/203282289-6dda5cc2-51b4-4c0f-8f3c-c713fce70d6e.png)

target 添加lun的时候指定blocksize，看到的是这样的

Target specifies the blocksize when adding lun, what you see is this

![image](https://user-images.githubusercontent.com/4277834/203283331-1eeaf463-3353-4649-b54d-db04625c8123.png)

2022-11-22 10:04 UTC, Wine93 commented on cli/command/target/add.go
> +	flags.StringVar(&options.blocksize, "blocksize", "512byte", "Specify volume block size")
The default unit of blocksize should be `Byte`, and if we want to provide more unit for convenience, we can use `KB`、`MB` and etc, like:

```
--blocksize 512  # Byte, also default unit
--blocksize 1KB  # KB
--blocksize 1MB  # MB
```

2022-11-22 10:09 UTC, Wine93 commented
BTW: there are many commits in this PR, maybe we can rebase them into one :)

2022-11-24 02:24 UTC, mfordjody commented
```
curve@client-hosts:~/1/curveadm/cmd/curveadm$ go run main.go target add curve:/test --host server-hosts --create --size 30GB --blocksize 512B
Add Target: [ERROR]
  + host=server-hosts  volume=/test [0/1] [ERROR]
---
Error-Code: 630009
Error-Description: run a command in container failed (docker exec CONTAINER COMMAND)
Error-Clue: tgtadm: failed to send request hdr to tgt daemon, Transport endpoint is not connected
            tgtadm target new failed
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno6#630009
  * Log: /home/curve/.curveadm/logs/curveadm-2022-11-24_10-21-01.log
  * WeChat: opencurve_bot
exit status 1
```
```
curve@client-hosts:~/1/curveadm/cmd/curveadm$ go run main.go target add curve:/test --host server-hosts --create --size 30GB --blocksize 1kB
---
Error-Code: 221011
Error-Description: volume block size be a multiple of 512B,like 1.024kB, 2.048kB,3.072kB...
Error-Clue: blocksize: 1.0 kB
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno2#221011
  * Log: /home/curve/.curveadm/logs/curveadm-2022-11-24_10-21-09.log
  * WeChat: opencurve_bot
exit status 1
```

2022-11-24 02:31 UTC, Cyber-SiKu commented
> ```
> curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test --host server-hosts --create --size 30GB --blocksize 512
> ---
> Error-Code: 201009
> Error-Description: volume block size must end with "B" suffix
> Error-Clue: blocksize: 512
> How to Solve:
>   * Website: https://github.com/opencurve/curveadm/wiki/errno2#201009
>   * Log: /home/curve/.curveadm/logs/curveadm-2022-11-24_10-25-10.log
>   * WeChat: opencurve_bot
> exit status 1
> ```
> 
> ```
> curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test --host server-hosts --create --size 30GB --blocksize 1kB
> ---
> Error-Code: 221011
> Error-Description: volume block size be a multiple of 512B,like 1.024kB, 2.048kB,3.072kB...
> Error-Clue: blocksize: 1.0 kB
> How to Solve:
>   * Website: https://github.com/opencurve/curveadm/wiki/errno2#221011
>   * Log: /home/curve/.curveadm/logs/curveadm-2022-11-24_10-21-09.log
>   * WeChat: opencurve_bot
> exit status 1
> ```

You can use the package [go-humanize](https://github.com/dustin/go-humanize) to parse string.

2022-11-24 02:40 UTC, Cyber-SiKu requested changes

2022-11-24 02:40 UTC, Cyber-SiKu commented on cli/command/client/map.go
> +	}
It is not needed here.

2022-11-24 03:25 UTC, mfordjody commented
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test --host server-hosts --create --size 10GB
Add Target: [OK]
  + host=server-hosts  volume=/test [1/1] [OK]

Add target (curve:/test) to server-hosts success ^_^
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test1 --host server-hosts --create --size 10GB --blocksize 512
Add Target: [OK]
  + host=server-hosts  volume=/test1 [1/1] [OK]

Add target (curve:/test1) to server-hosts success ^_^
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test1 --host server-hosts --create --size 10GB --blocksize 1k
---
Error-Code: 221011
Error-Description: volume block size be a multiple of 512B,like 1.024kB, 2.048kB,3.072kB...
Error-Clue: blocksize: 1.0 kB
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno2#221011
  * Log: /home/curve/.curveadm/logs/curveadm-2022-11-24_11-23-51.log
  * WeChat: opencurve_bot
exit status 1
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test2 --host server-hosts --create --size 10GB --blocksize 4.096k
Add Target: [OK]
  + host=server-hosts  volume=/test2 [1/1] [OK]

Add target (curve:/test2) to server-hosts success ^_^
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target list --host server-hosts
List Targets: [OK]
  + host=192.168.10.143 [1/1] [OK]

Tid  Host          Target Name                                                       Store                   Portal
---  ----          -----------                                                       -----                   ------
1    server-hosts  iqn.2022-11.com.opencurve:curve.5a82e0b942bc472fe1de2059b971b7bd  cbd:pool//test_curve_   192.168.10.143:3260
2    server-hosts  iqn.2022-11.com.opencurve:curve.d97372e236558863e4ffc63dcfa7eb27  cbd:pool//test1_curve_  192.168.10.143:3260
3    server-hosts  iqn.2022-11.com.opencurve:curve.41f7dfa48ebe871dd74b2db0d88f1243  cbd:pool//test2_curve_  192.168.10.143:3260
```

2022-11-24 03:29 UTC, mfordjody commented on cli/command/client/map.go
> +	}
done

2022-11-24 07:32 UTC, Cyber-SiKu requested changes

2022-11-24 07:32 UTC, Cyber-SiKu commented on cli/command/client/map.go
> +	blocksize = strings.TrimSuffix(blocksize, "B")
No need to remove B.
```
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"

	"github.com/dustin/go-humanize"
)

func main() {
	blocksize := "1024B"
	str, _ := humanize.ParseBytes(blocksize)
	fmt.Println(str)
}
```
the output is:
```
1024
```

2022-11-24 07:32 UTC, Cyber-SiKu commented on cli/command/client/map.go
> +			F("blocksize: %s", humanize.Bytes(m))
humanize.IBytes(m)

2022-11-24 07:32 UTC, Cyber-SiKu commented on cli/command/client/map.go
> +			F("blocksize: %s", humanize.Bytes(m))
ditto

2022-11-24 07:32 UTC, Cyber-SiKu commented on cli/command/client/map.go
> +	m, err := humanize.ParseBytes(blocksize)
You can look at its [source code](https://github.com/dustin/go-humanize/blob/master/bytes.go)

2022-11-24 07:32 UTC, Cyber-SiKu commented on cli/command/client/map.go
> +			F("blocksize: %s", humanize.Bytes(m))
Learn the difference between Bytes and IBytes:[Multiple-byte units](https://en.wikipedia.org/wiki/Byte#Multiple-byte_units)

2022-11-24 07:32 UTC, Cyber-SiKu commented on cli/command/client/map.go
>  	flags.StringVar(&options.size, "size", "10GB", "Specify volume size")
GiB?

2022-11-24 07:32 UTC, Cyber-SiKu commented on cli/command/target/add.go
>  	flags.StringVar(&options.size, "size", "10GB", "Specify volume size")
ditto

2022-11-24 07:32 UTC, Cyber-SiKu commented on internal/errno/errno.go
> +	ERR_VOLUME_SIZE_MUST_BE_MULTIPLE_OF_10_GB      = EC(221005, "volume size must be a multiple of 10GB, like 10GB, 20GB, 30GB...")
ditto

2022-11-24 07:32 UTC, Cyber-SiKu commented on internal/errno/errno.go
> +	ERR_VOLUME_BLOCKSIZE_BE_MULTIPLE_OF_512        = EC(221011, "volume block size be a multiple of 512B,like 1.024kB, 2.048kB,3.072kB...")
ditto

2022-11-24 09:55 UTC, mfordjody commented
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add -h
Usage:  curveadm target add USER:VOLUME [OPTIONS]

Add a target of CurveBS

Options:
      --blocksize string   Specify volume blocksize (default "512B")
  -c, --conf string        Specify client configuration file (default "client.yaml")
      --create             Create volume iff not exist
  -h, --help               Print usage
      --host string        Specify target host (default "localhost")
      --size string        Specify volume size (default "10GiB")
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test --host server-hosts --create --size 10GB
---
Error-Code: 221003
Error-Description: volume size must end with "GiB" suffix
Error-Clue: size: 10GB
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno2#221003
  * Log: /home/curve/.curveadm/logs/curveadm-2022-11-24_17-54-56.log
  * WeChat: opencurve_bot
exit status 1
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test --host server-hosts --create --size 10GiB
Add Target: [OK]
  + host=server-hosts  volume=/test [1/1] [OK]
Add target (curve:/test) to server-hosts success ^_^
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test1 --host server-hosts --create --size 10GiB --blocksize 512
---
Error-Code: 201009
Error-Description: volume block size must end with "B" suffix
Error-Clue: blocksize: 512
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno2#201009
  * Log: /home/curve/.curveadm/logs/curveadm-2022-11-24_17-50-10.log
  * WeChat: opencurve_bot
exit status 1
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test1 --host server-hosts --create --size 10GiB --blocksize 512B
Add Target: [OK]
  + host=server-hosts  volume=/test1 [1/1] [OK]

Add target (curve:/test1) to server-hosts success ^_^
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test2 --host server-hosts --create --size 10GiB --blocksize 1kiB
Add Target: [OK]
  + host=server-hosts  volume=/test2 [1/1] [OK]

Add target (curve:/test2) to server-hosts success ^_^
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test2 --host server-hosts --create --size 10GiB --blocksize 1kiB
Add Target: [ERROR]
  + host=server-hosts  volume=/test2 [0/1] [ERROR]
---
Error-Code: 630009
Error-Description: run a command in container failed (docker exec CONTAINER COMMAND)
Error-Clue: tgtadm: this target already exists
            tgtadm target new failed
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno6#630009
  * Log: /home/curve/.curveadm/logs/curveadm-2022-11-24_17-50-44.log
  * WeChat: opencurve_bot
exit status 1
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ cat /home/curve/.curveadm/logs/curveadm-2022-11-24_17-50-44.log
2022-11-24 17:50:45     [ERR]:  (log.go:109):   Execute command
    remoteAddr: curve@192.168.10.143:22
    command: sudo docker exec  curvebs-target-daemon /bin/bash /curvebs/tools/sbin/target.sh curve /test2 true 10 1024
    output: tgtadm: this target already exists
tgtadm target new failed
    error: Process exited with status 1
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target list --host server-hosts
List Targets: [OK]
  + host=192.168.10.143 [1/1] [OK]

Tid  Host          Target Name                                                       Store                   Portal
---  ----          -----------                                                       -----                   ------
1    server-hosts  iqn.2022-11.com.opencurve:curve.5a82e0b942bc472fe1de2059b971b7bd  cbd:pool//test_curve_   192.168.10.143:3260
2    server-hosts  iqn.2022-11.com.opencurve:curve.d97372e236558863e4ffc63dcfa7eb27  cbd:pool//test1_curve_  192.168.10.143:3260
3    server-hosts  iqn.2022-11.com.opencurve:curve.41f7dfa48ebe871dd74b2db0d88f1243  cbd:pool//test2_curve_  192.168.10.143:3260
```

2022-11-24 09:59 UTC, mfordjody commented
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test --host server-hosts --create --size 30GiB --blocksize 4kiB
Add Target: [OK]
  + host=server-hosts  volume=/test [1/1] [OK]

Add target (curve:/test) to server-hosts success ^_^
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go target add curve:/test --host server-hosts --create --size 30GiB --blocksize 4kiB
Add Target: [ERROR]
  + host=server-hosts  volume=/test [0/1] [ERROR]
---
Error-Code: 630009
Error-Description: run a command in container failed (docker exec CONTAINER COMMAND)
Error-Clue: tgtadm: this target already exists
            tgtadm target new failed
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno6#630009
  * Log: /home/curve/.curveadm/logs/curveadm-2022-11-24_17-57-32.log
  * WeChat: opencurve_bot
exit status 1
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ cat /home/curve/.curveadm/logs/curveadm-2022-11-24_17-57-32.log
2022-11-24 17:57:34     [ERR]:  (log.go:109):   Execute command
    remoteAddr: curve@192.168.10.143:22
    command: sudo docker exec  curvebs-target-daemon /bin/bash /curvebs/tools/sbin/target.sh curve /test true 30 4096
    output: tgtadm: this target already exists
tgtadm target new failed
    error: Process exited with status 1
```

2022-11-25 06:08 UTC, Cyber-SiKu commented on cli/command/client/map.go
> +	if !strings.HasSuffix(size, "GiB") {
size must be GiB？

2022-11-25 06:09 UTC, Cyber-SiKu reviewed
Merge multiple commits into one.

2022-11-25 09:24 UTC, mfordjody commented
done

2022-11-25 09:33 UTC, Cyber-SiKu approved these changes
LGTM!

2022-11-28 06:38 UTC, cw123 commented on cli/command/client/map.go
> +	flags.StringVar(&options.blocksize, "blocksize", "512B", "Specify volume blocksize")
default 4096B

2022-11-28 07:38 UTC, mfordjody commented on cli/command/client/map.go
> +	flags.StringVar(&options.blocksize, "blocksize", "512B", "Specify volume blocksize")
done

2022-11-28 08:34 UTC, cw123 commented
看起来有两个地方都增加了blocksize的改动，一个map的时候，一个是add target的时候。

map的地方，map命令使用curve-nbd map，这个接收的参数不包含blocksize，而且这个命令没有测试结果。

另一个是add target的地方，看起主要逻辑是正确的，遗漏了一点，blocksize默认应该是4096B。

请确认一下，map.go中的逻辑是否正确。

It seems that there are two places where the changes of blocksize have been added, one for map and one for add target.

For map, the map command uses curve-nbd map, the received parameter does not include blocksize, and this command has no test results.

The other is add target. It seems that the main logic is correct. One thing is missing. The default blocksize should be 4096B.

Please confirm whether the logic in map.go is correct.

2022-11-28 09:05 UTC, mfordjody commented
> 看起来有两个地方都增加了blocksize的改动，一个map的时候，一个是add target的时候。
> 
> map的地方，map命令使用curve-nbd map，这个接收的参数不包含blocksize，而且这个命令没有测试结果。
> 
> 另一个是add target的地方，看起主要逻辑是正确的，遗漏了一点，blocksize默认应该是4096B。
> 
> 请确认一下，map.go中的逻辑是否正确。
> 
> It seems that there are two places where the changes of blocksize have been added, one for map and one for add target.
> 
> For map, the map command uses curve-nbd map, the received parameter does not include blocksize, and this command has no test results.
> 
> The other is add target. It seems that the main logic is correct. One thing is missing. The default blocksize should be 4096B.
> 
> Please confirm whether the logic in map.go is correct.

这个默认值应该自定义，让用户自己选择。保证他是512整数倍即可。

This default value should be customized for users to choose. Make sure he is an integral multiple of 512

2022-11-28 12:31 UTC, mfordjody commented
我将 add 里面默认值修改成 4096B，现在他默认就是 4096B 了

I changed the default value of add to 4096B, and now it is 4096B by default

2022-11-28 14:49 UTC, mfordjody commented
```
root@client-hosts:/home/curve/curveadm/cmd/curveadm# go run main.go target add curve:/test1 --host server-hosts --create --size 30GiB
Add Target: [OK]
  + host=server-hosts  volume=/test1 [1/1] [OK]

Add target (curve:/test1) to server-hosts success ^_^
```
```
root@client-hosts:/home/curve/curveadm/cmd/curveadm# go run main.go target add curve:/test1 --host server-hosts --create --size 30GiB
Add Target: [ERROR]
  + host=server-hosts  volume=/test1 [0/1] [ERROR]
---
Error-Code: 630009
Error-Description: run a command in container failed (docker exec CONTAINER COMMAND)
Error-Clue: tgtadm: this target already exists
            tgtadm target new failed
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno6#630009
  * Log: /root/.curveadm/logs/curveadm-2022-11-28_22-48-41.log
  * WeChat: opencurve_bot
exit status 1
```
```
root@client-hosts:/home/curve/curveadm/cmd/curveadm# cat /root/.curveadm/logs/curveadm-2022-11-28_22-48-41.log
2022-11-28 22:48:42     [ERR]:  (log.go:109):   Execute command
    remoteAddr: curve@192.168.10.143:22
    command: sudo docker exec  curvebs-target-daemon /bin/bash /curvebs/tools/sbin/target.sh curve /test1 true 30 4096
    output: tgtadm: this target already exists
tgtadm target new failed
    error: Process exited with status 1
```

2022-11-28 14:52 UTC, mfordjody commented
```
root@client-hosts:/home/curve/curveadm/cmd/curveadm# go run main.go target add curve:/test2 --host server-hosts --create --size 20GiB --blocksize 1kiB
Add Target: [OK]
  + host=server-hosts  volume=/test2 [1/1] [OK]

Add target (curve:/test2) to server-hosts success ^_^
```
```
root@client-hosts:/home/curve/curveadm/cmd/curveadm# go run main.go target add curve:/test2 --host server-hosts --create --size 20GiB --blocksize 1kiB
Add Target: [ERROR]
  + host=server-hosts  volume=/test2 [0/1] [ERROR]
---
Error-Code: 630009
Error-Description: run a command in container failed (docker exec CONTAINER COMMAND)
Error-Clue: tgtadm: this target already exists
            tgtadm target new failed
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno6#630009
  * Log: /root/.curveadm/logs/curveadm-2022-11-28_22-50-12.log
  * WeChat: opencurve_bot
exit status 1
```
```
root@client-hosts:/home/curve/curveadm/cmd/curveadm# cat /root/.curveadm/logs/curveadm-2022-11-28_22-50-12.log
2022-11-28 22:50:13     [ERR]:  (log.go:109):   Execute command
    remoteAddr: curve@192.168.10.143:22
    command: sudo docker exec  curvebs-target-daemon /bin/bash /curvebs/tools/sbin/target.sh curve /test2 true 20 1024
    output: tgtadm: this target already exists
tgtadm target new failed
    error: Process exited with status 1
```

2022-11-29 06:47 UTC, cw123 commented
test map command

https://github.com/opencurve/curveadm/wiki/curvebs-client-deployment#%E7%AC%AC-4-%E6%AD%A5%E6%98%A0%E5%B0%84-curvebs-%E5%8D%B7

2022-11-29 08:20 UTC, mfordjody commented
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go map curve:/test --host server-hosts -c client.yaml --create --size 10GiB
Check Kernel Module: [OK]
  + host=server-hosts  module=nbd [1/1] [OK]

Start NEBD Service: [OK]
  + hostname=192.168.10.143  image=opencurvedocker/curvebs:v1.2 [1/1] [OK]

Create Volume: [OK]
  + hostname=192.168.10.143  image=opencurvedocker/curvebs:v1.2 [1/1] [OK]

Map Volume: [OK]
  + hostname=192.168.10.143  volume=curve:/test [1/1] [OK]

Map curve:/test to server-hosts nbd device success ^_^
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go map curve:/test --host server-hosts -c client.yaml --create --size 10GiB
Check Kernel Module: [OK]
  + host=server-hosts  module=nbd [1/1] [OK]

Start NEBD Service: [ERROR]
  + hostname=192.168.10.143  image=opencurvedocker/curvebs:v1.2 [0/1] [ERROR]
---
Error-Code: 420000
Error-Description: volume already mapped
Error-Clue: volume: curve:/test
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno4#420000
  * Log: /home/curve/.curveadm/logs/curveadm-2022-11-29_16-01-15.log
  * WeChat: opencurve_bot
exit status 1
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ cat /home/curve/.curveadm/logs/curveadm-2022-11-29_16-01-15.log
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ go run main.go map curve:/test1 --host server-hosts -c client.yaml --create --size 10GiB --blocksize 4kiB
Check Kernel Module: [OK]
  + host=server-hosts  module=nbd [1/1] [OK]

Start NEBD Service: [OK]
  + hostname=192.168.10.143  image=opencurvedocker/curvebs:v1.2 [1/1] [OK]

Create Volume: [OK]
  + hostname=192.168.10.143  image=opencurvedocker/curvebs:v1.2 [1/1] [OK]

Map Volume: [OK]
  + hostname=192.168.10.143  volume=curve:/test1 [1/1] [OK]

Map curve:/test1 to server-hosts nbd device success ^_^
```
```
curve@client-hosts:~/curveadm/cmd/curveadm$ curveadm client status
Get Client Status: [OK]

Id            Kind     Host          Container Id  Status             Aux Info
--            ----     ----          ------------  ------             --------
d056f4d680dd  curvebs  server-hosts  2a7d0b491f2b  Up 25 seconds      {"user":"curve","volume":"/test1"}
b96b111a2066  curvebs  server-hosts  356ed3034de8  Up About a minute  {"user":"curve","volume":"/test"}
```

2022-12-01 08:01 UTC, cw123 approved these changes

2022-12-01 11:01 UTC, merged